env:
  browser: true
  es2021: true
  node: true

extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier

overrides:
  - env:
      node: true
    files:
      - .eslintrc.{js,cjs}
    parserOptions:
      sourceType: script

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'

rules: {}